### ISSUE TITLE
Uncaught error: Parse error (Lex error at (2, 10) input: 0.2.0

### ISSUE THREAD

**Issue by teto** [berewt/REPLica#30]
This is my first experience with an idris program and I would like to try it on NixOS (www.nixos.org).
When I try to run the commande in the Makefile, I get an error
```
idris2 --install replica.ipkg
Uncaught error: Parse error (Lex error at (2, 10) input: 0.2.0

sourcedir = "src"
```
with
```
idris2 --version
Idris 2, version 0.3.0
```

I have removed the line with version from the .ipkg file and that solved that error but triggered anotherone:
```
(ins)➜ idris2 --install replica.ipkg
1/25: Building Replica.App.FileSystem (src/Replica/App/FileSystem.idr)
Error: Module Data.String not found

src/Replica/Other/String.idr:4:1--4:19
   |
 4 | import Data.String
   | ^^^^^^^^^^^^^^^^^^
```
In the Idris REPL, if I do `:module Data.Strings` it seems to work. I wonder if replica is realy idris2 compatible or if it's a missing dependency or sthg else ?

**Comment by berewt** [comment]
At the moment, most idris users use the latest idris (usually build from source). v0.3.0 is a bit behind.

Regarding `Data.String`, it was called `Data.Strings` in 0.3.0. I'm not sure about the ipkg lexer issue, I don't remember how it was done in 0.3.0.

Thanks to bring it to the table, I have to specify the version to use in the readme. I'm not sure if you can easily switch to a more recent version of Idris in nix to be honest. As I'm not (yet) a nix user.

I hope it helps, thanks again.

**Comment by berewt** [comment]
Note: I've disscussed with the development team, an official release may be out soon, I'll try to stick to that one in the future.

**Comment by teto** [comment]
thanks. I've tried bumping the idris version but seems like it requires more time  than I am ready to commit at the moment.

A good practice (I find) in READMEs is to list the "competition", it makes it easier to frame the project intentions etc so you may want to reference https://hackage.haskell.org/package/shelltestrunner that I was looking into but replica seems better suited.

**Comment by berewt** [comment]
That's a good idea. I included a few lines about it in the readme. Regarding nix, there's a dedicated channel about it on the[ idris discord](https://discord.gg/UX68fDs2jc), you may find some help here.

**Comment by teto** [comment]
thanks for making me check twice, the idris2 repo has a nix flake so getting the master version of idris was as simple as running `nix run github:idris-lang/idris2` !

make install complains about not being able to create a folder but  I can run the binary from `build/exec`. 
```
➜ make install                                                                                                                                                                        ~/REPLica
idris2 --install replica.ipkg
Uncaught error: INTERNAL ERROR: Can't make directory replica-0.2.0
File error: 30
```

**Comment by berewt** [comment]
It's getting better! 

`make install` try to create a `${HOME}/.local/bin` directory and then copy the content of `build/exec` in it. For some reasons, the last step fails for you. Maybe it's a right issue?

**Comment by teto** [comment]
strace shows something weird, idris2 tries to create the folder in the folder where the idris2 binary is (the nix store is read-only). Not sure if that's an idris weird behavior or just an artifcat of the packaging.
```
725697 chdir("/nix/store/xm3f8radf1y3abji0m9i8f8apvxg16jx-idris2-0.3.0/idris2-0.3.0") = 0
725697 openat(AT_FDCWD, "replica-0.2.0", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
725697 mkdir("replica-0.2.0", 0777)     = -1 EROFS (Read-only file system)
725697 chdir("/home/teto/REPLica")      = 0
725697 fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0xd), ...}) = 0
725697 write(1, "Uncaught error: INTERNAL ERROR: "..., 67) = 67
725697 write(1, "File error: 30\n", 15) = 15
```

**Comment by teto** [comment]
I asked on the discord where they advised me to run `nix flake init -t github:idris-lang/Idris2` and it created a working flake straightaway !! it's possible to run replica via `nix run github:teto/REPLica/nix`. I can open a PR if you are interested.

**Comment by teto** [comment]
just was able to run my first run, it worked beautifully and is exactly what I was looking for. I've seen diffing output with golden-test is an accepted project, it is already working ? Now trying the dhall generation (Good idea !)

**Comment by berewt** [comment]
The PR for nix would be great, I was thinking of it but didn't have time to dive in nix to grasp how it would work. It sounds awesome.

It's hearthwarming to read such a positive feedback. For some reason, I forgot to include the diff if we don't run in an interactive mode. I have to fix it. Ideally, being able to go back to the current mode with a `--compact` flag and having the diff on a normal output would be great.

Regarding dhall, it was clear for me when I started playing with config file that it would help to provide a way to easily provide tests templates, dhall is really great at it. As it should be stated in the readme, you can look how replica tests are written if you want to try dhall configurations.

**Comment by teto** [comment]
I opened https://github.com/berewt/REPLica/pull/36 which makes it trivial to build/develop REPLica. 
I 've just tried to update my test suite and so was looking to versionize in git the golden outputs.

After running in verbose mode, I could see that a `.replica` folder was created. It seems like the golden output is there (sad it doesn't appear there). 
It seems a bit strange to put the golden outputs in a hidden folder since you are likely to put them in git (or your VCS) ?!

```
Replica directory: /home/teto/quantum/.replica
Plan:
  Now: ["hello"]
  Later: []
  Skipped: []
--------------------------------------------------------------------------------
Running tests...
Executing hello
  Working directory: "."
  Running command: (echo "Hello, world!")  > "/home/teto/quantum/.replica/test/hello/output"
  ```
